### ISSUE TITLE
念到“特”就没声了

### ISSUE THREAD

**Issue by CarryWS** [DSP-8192/HuoZiYinShua#9]
参见下面这个
链接：https://pan.baidu.com/s/1CchX7lDo181aS59kPQjBBA 
提取码：otto
台词：你说得对，但是《原神》是由米哈游自主研发的一款全新开放世界冒险游戏。游戏发生在一个被称作“提瓦特”的幻想世界，在这里，被神选中的人将被授予“神之眼”，导引元素之力。你将扮演一位名为“旅行者”的神秘角色，在自由的旅行中邂逅性格各异、能力独特的同伴们，和他们一起击败强敌，找回失散的亲人——同时，逐步发掘“原神”的真相。

**Comment by CarryWS** [comment]
队友呢？救一下啊！

**Comment by niconicozha** [comment]
我直接先从source里面复制de到另一个文件夹，然后重命名为te，再放进source里面

**Comment by CarryWS** [comment]
也行的，我那天刷遍电棍语录想找个“te”的音源，但是没这方面的经验，电棍语速太快了，自己采的音源效果不好
